<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Token</name>
   <tag></tag>
   <elementGuidId>da758675-b6d1-4b1c-b0ec-a0a02106fdcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d758d0cf-4eca-4719-aa06-c94af8c2458b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFNDg3NzRDMjM2RENBODM5MDAzMEM2NTkzMUY3Q0RBIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDAzIiwibmJmIjoxNjc5NjI5MTY5LCJpYXQiOjE2Nzk2MjkxNjksImV4cCI6MTY3OTYzMjc2OSwiYXVkIjpbIndlYXRoZXJhcGkiLCJodHRwczovL2xvY2FsaG9zdDo3MDAzL3Jlc291cmNlcyJdLCJzY29wZSI6WyJ3ZWF0aGVyLnJlYWQiLCJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJpbnRlcmFjdGl2ZSIsInN1YiI6IjRjZjVkZDM2LWY0N2EtNDVjMy1hN2U1LWE5Y2UxOWNlMWE4ZiIsImF1dGhfdGltZSI6MTY3OTYyOTE2MCwiaWRwIjoibG9jYWwiLCJzaWQiOiJBNENGQzY2ODA3N0JDRjk2ODlFOUNEOTI1NEMwNzUzQiIsImp0aSI6IkVFMzA0MDMwOTc5RUZENTIzNzQxRkNDQjNDNTA1RDM3In0.bMToSCYoWEW2IIIUhCwRFolelzuUCZQqdxWAfWUtSah1n4eO9kV1jh3aLGGX7g77jhIJ9yZPK3AgHjWjQGTsyKau8Al-_arR5z_GAEY1IRSmtPV2WtvOWGBUR4Aj7dgU5oHpmCnnrPcJCpsySgx_rPigLixqU3K2a_-7ODojOXpK00_43Ygiy_8HlhJlrNbrEHZpfmIgfXy3LqkBlKwZUXsTNe-mwcjcKBzJqgonozZPARGBEBQWIJTs7iaP3PQHppjMiYyDA-Br6vCvghHMqCNDYQ0z1ePNmawEs2-X4TpcZOqwCD_MhwXYE6bvyFU8Pz25Z-N7hTVhcbnlWVyS_g</value>
      <webElementGuid>5f9516b8-de93-4a29-a7e2-573b6559abed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[2]/p[2]</value>
      <webElementGuid>ab392cc2-92cb-49f9-9c86-1df1a5982927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/p[2]</value>
      <webElementGuid>607589d9-ff26-4900-a650-05dc29a80ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::p[2]</value>
      <webElementGuid>5b6b7097-7fc9-4c34-ae9b-312d6aa7274b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'root', '&quot;', ')/div[@class=', '&quot;', 'App', '&quot;', ']/div[2]/p[2]')])[1]/preceding::p[2]</value>
      <webElementGuid>fc239f91-20a3-4613-b9dd-8e5e38cb232e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Token:']/parent::*</value>
      <webElementGuid>f7653be4-5e35-42a9-a2b4-12c1ce37fe1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>96bacb61-eb32-4c15-9c96-989cb725e166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFNDg3NzRDMjM2RENBODM5MDAzMEM2NTkzMUY3Q0RBIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDAzIiwibmJmIjoxNjc5NjI5MTY5LCJpYXQiOjE2Nzk2MjkxNjksImV4cCI6MTY3OTYzMjc2OSwiYXVkIjpbIndlYXRoZXJhcGkiLCJodHRwczovL2xvY2FsaG9zdDo3MDAzL3Jlc291cmNlcyJdLCJzY29wZSI6WyJ3ZWF0aGVyLnJlYWQiLCJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJpbnRlcmFjdGl2ZSIsInN1YiI6IjRjZjVkZDM2LWY0N2EtNDVjMy1hN2U1LWE5Y2UxOWNlMWE4ZiIsImF1dGhfdGltZSI6MTY3OTYyOTE2MCwiaWRwIjoibG9jYWwiLCJzaWQiOiJBNENGQzY2ODA3N0JDRjk2ODlFOUNEOTI1NEMwNzUzQiIsImp0aSI6IkVFMzA0MDMwOTc5RUZENTIzNzQxRkNDQjNDNTA1RDM3In0.bMToSCYoWEW2IIIUhCwRFolelzuUCZQqdxWAfWUtSah1n4eO9kV1jh3aLGGX7g77jhIJ9yZPK3AgHjWjQGTsyKau8Al-_arR5z_GAEY1IRSmtPV2WtvOWGBUR4Aj7dgU5oHpmCnnrPcJCpsySgx_rPigLixqU3K2a_-7ODojOXpK00_43Ygiy_8HlhJlrNbrEHZpfmIgfXy3LqkBlKwZUXsTNe-mwcjcKBzJqgonozZPARGBEBQWIJTs7iaP3PQHppjMiYyDA-Br6vCvghHMqCNDYQ0z1ePNmawEs2-X4TpcZOqwCD_MhwXYE6bvyFU8Pz25Z-N7hTVhcbnlWVyS_g' or . = 'Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFNDg3NzRDMjM2RENBODM5MDAzMEM2NTkzMUY3Q0RBIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDAzIiwibmJmIjoxNjc5NjI5MTY5LCJpYXQiOjE2Nzk2MjkxNjksImV4cCI6MTY3OTYzMjc2OSwiYXVkIjpbIndlYXRoZXJhcGkiLCJodHRwczovL2xvY2FsaG9zdDo3MDAzL3Jlc291cmNlcyJdLCJzY29wZSI6WyJ3ZWF0aGVyLnJlYWQiLCJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJpbnRlcmFjdGl2ZSIsInN1YiI6IjRjZjVkZDM2LWY0N2EtNDVjMy1hN2U1LWE5Y2UxOWNlMWE4ZiIsImF1dGhfdGltZSI6MTY3OTYyOTE2MCwiaWRwIjoibG9jYWwiLCJzaWQiOiJBNENGQzY2ODA3N0JDRjk2ODlFOUNEOTI1NEMwNzUzQiIsImp0aSI6IkVFMzA0MDMwOTc5RUZENTIzNzQxRkNDQjNDNTA1RDM3In0.bMToSCYoWEW2IIIUhCwRFolelzuUCZQqdxWAfWUtSah1n4eO9kV1jh3aLGGX7g77jhIJ9yZPK3AgHjWjQGTsyKau8Al-_arR5z_GAEY1IRSmtPV2WtvOWGBUR4Aj7dgU5oHpmCnnrPcJCpsySgx_rPigLixqU3K2a_-7ODojOXpK00_43Ygiy_8HlhJlrNbrEHZpfmIgfXy3LqkBlKwZUXsTNe-mwcjcKBzJqgonozZPARGBEBQWIJTs7iaP3PQHppjMiYyDA-Br6vCvghHMqCNDYQ0z1ePNmawEs2-X4TpcZOqwCD_MhwXYE6bvyFU8Pz25Z-N7hTVhcbnlWVyS_g')]</value>
      <webElementGuid>387efd12-625e-4361-8b81-ff2311687303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
