<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Editor</name>
   <tag></tag>
   <elementGuidId>15ee4eb5-fb34-45fd-80bc-cdc4cfb1ddb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/div/div/nav/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73542a00-a206-4103-a4df-6b52e0be82e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navegacion__enlace</value>
      <webElementGuid>ddf992bc-90f1-4f0a-9986-8bd811238e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/editor</value>
      <webElementGuid>66b76dd0-fd7f-4a4f-9c0d-5620d1f3c57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editor</value>
      <webElementGuid>14cb4cf2-be0c-4bad-8884-d5a488b1699c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;homepage&quot;]/header[1]/div[@class=&quot;contenedor&quot;]/div[@class=&quot;barra&quot;]/nav[@class=&quot;navegacion&quot;]/a[@class=&quot;navegacion__enlace&quot;]</value>
      <webElementGuid>723fd294-6b91-4c9a-9ccd-f0eb986202a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/div/div/nav/a[2]</value>
      <webElementGuid>0d261f7d-6661-468b-a544-e3817a2af187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Editor')]</value>
      <webElementGuid>ffa3b735-7fe7-4edb-94b1-df471033f7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nosotros'])[1]/following::a[1]</value>
      <webElementGuid>d61cd03d-b9ef-41c9-9bf9-affaa0be248e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::a[2]</value>
      <webElementGuid>a2d28eeb-6d57-4803-9554-f1acd9e8d483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conceptos'])[1]/preceding::a[1]</value>
      <webElementGuid>ae749da4-77d3-47ac-bf42-21f8ebc3a12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacto'])[1]/preceding::a[2]</value>
      <webElementGuid>7ee67a04-1567-41ec-ac4d-d4a0db46f4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editor']/parent::*</value>
      <webElementGuid>b0e9e200-fc42-4e19-b446-e1ccc213ae31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/editor')]</value>
      <webElementGuid>e88bfa33-bdb2-4cad-b7c9-f20b5c8f15a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>c44417a8-c973-44b7-86b2-df84e8256f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/editor' and (text() = 'Editor' or . = 'Editor')]</value>
      <webElementGuid>911d3cc4-1572-440d-9c14-86203b6314a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
