<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Code</name>
   <tag></tag>
   <elementGuidId>71b1c7bf-4a9c-4dbb-8162-25ade67e572a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fw-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/nav/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7852f1d-6fe3-4f1b-91c2-c4f17e9d11ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold</value>
      <webElementGuid>8906a0cc-ba65-4716-a89e-15c6c4040d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>ed9579b4-8377-4e30-846b-fd29a1b69727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/header[1]/nav[@class=&quot;navbar navbar-expand-lg navbar-dark bg-dark&quot;]/div[@class=&quot;container-fluid&quot;]/a[@class=&quot;navbar-brand&quot;]/span[@class=&quot;fw-bold&quot;]</value>
      <webElementGuid>430a69cd-03da-405c-976c-99c9280d1517</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/nav/div/a/span</value>
      <webElementGuid>19d6c223-a0d8-433a-bb0b-f8e44440831d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editor'])[1]/preceding::span[2]</value>
      <webElementGuid>994e0aa4-bf47-4f18-8d47-0c75b4f8a683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conceptos'])[1]/preceding::span[2]</value>
      <webElementGuid>800e56de-8329-46bf-a961-940cfb10f648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Code']/parent::*</value>
      <webElementGuid>5d797024-bffa-4bb1-be14-11746beb65df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>1df2428f-b4a1-4960-abdc-c63d6f9a024f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Code' or . = 'Code')]</value>
      <webElementGuid>8e07b5c5-a66e-41bb-ae95-2ff155aedb96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
